### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by gisbi-kim** [ethz-asl/dynablox#1]
Thanks for the great work and sharing. 

I have a couple of questions 
1. outdoor results or videos are available? 
2. any tips to tune parameters for outdoor (i.e., more sparse and fast dynamic objects, even more ego pose errors) datasets?

**Comment by Schmluk** [comment]
Hi @gisbi-kim 

Thanks for reaching out!

1. Some of the DOALS as well as our own sequences are outdoors, some of them are depicted in the paper and video.
2. Can you be more specific? We ran the same parametrization outdoors and it worked well in our cases. Also fast moving objects should not be a problem.

Hope this helps!

**Comment by gisbi-kim** [comment]
I would like test the dynablox for my own fast moving driving cars (e.g., 30-60km/h) in urban environments. i.e., the moving objects contains mostly cars, as well as the people, as like in DOALS dataset (ps. I tested the DOALS dataset and I love the awesome result on it). The height of the top lidar horizontally mounted on a car is particularly higher than that of the DOALS dataset (e.g., 2-3m). In addition, I am curious about how robust it will be to pose estimation errors (for example, since there may be position errors of several tens of centimeters, especially for high-speed vehicles).

Of course, I don't mean to imply that Dynablox should solve all of these issues; rather, I just enjoy discussing my curiosities casually with the academia :) thanks for the fast response.

**Comment by gisbi-kim** [comment]
@Schmluk , thx for the very kind tips!

**Comment by Kin-Zhang** [comment]
I refactored all code and tried on KITTI:

https://user-images.githubusercontent.com/35365764/236311272-3d580f7d-579c-4185-b52a-e62600242022.mp4

Maybe need some parameter tunning suggestions, Hahaha.. 😀

**Comment by muzi2045** [comment]
looks like the param need to be modifyed in urban environment. LOL +_+. @Kin-Zhang
