### ISSUE TITLE
Any plans for ROS 2 ? 

### ISSUE THREAD

**Issue by JaYNits** [ethz-asl/dynablox#17]

**Comment by JaYNits** [comment]
@Schmluk

**Comment by Schmluk** [comment]
Hi @JaYNits 

Apologies for the late reply. We are currently not actively planning a ROS2 release in the short term. However, the code is setup in a way that almost everything is in the core C++ library and only the separate ROS library needs to be replaced by ROS2. If you happen implement a ROS2 version please feel free to open a PR!
