### ISSUE TITLE
Detections are stucking on rviz

### ISSUE THREAD

**Issue by lidiaxp** [ethz-asl/dynablox#18]
Thank you for open source this great framework.

I am running the package in the docker environment. My computer is an Intel® Core™ i9-10900X CPU @ 3.70GHz × 20I, with a NVIDIA Corporation TU102 [GeForce RTX 2080 Ti], and 128.0 GiB of RAM.

I have downloaded hauptgebaeude_sequence_1 in DOASL for testing. The simulations on Rviz are slow and stuck.

https://github.com/ethz-asl/dynablox/assets/12784079/5acfc79d-e3ef-46fe-8f1f-0f90c9b18e8f

I would be grateful for any help!

**Comment by Schmluk** [comment]
Hi @lidiaxp 

Have you tried running without RVIZ (and e.g. print the frame rate)? Your machine should definitively be able to run Dynablox at a high rate, sometimes RVIZ itself is not very quick (e.g. if there's some graphics drivers issues in some cases).

**Comment by lidiaxp** [comment]
Hello @Schmluk, I've just tested it. Even when I don't open RVIZ, the frame rate remains at 0.16 Hz.

I've also examined the point cloud frame rate, and it fluctuates between 8 and 14 Hz. So, I'm not sure why Dynablox is experiencing performance issues.

**Comment by Kin-Zhang** [comment]
I think maybe it's similar what I met before: https://github.com/ethz-asl/dynablox/issues/7#issuecomment-1535796272

Try to make it with Release Type:

```
catkin config --cmake-args -DCMAKE_BUILD_TYPE=Release
```

**Comment by lidiaxp** [comment]
It worked, thank you very much. Do you know why do we need it?

**Comment by Kin-Zhang** [comment]
Great, it helps you!

Mainly because of the `cmake type`, `release` will have o2 optimization.

**Comment by lidiaxp** [comment]
Oh, I got it, I haven't known it was possible to change this in ROS. I am going to read more about it. Thank you very much for your help.
