### ISSUE TITLE
Not identifying dynamic obstacles

### ISSUE THREAD

**Issue by lidiaxp** [ethz-asl/dynablox#20]
I am having problems to identify dynamic obstacles. I am using the default config file. Dynablox is identifying the static obstacles very well and in real time but the moving obstacle in the environment is also being classified as static. In the video is possible to see the static obstacle (labeled by dynablox) moving. 

https://github.com/ethz-asl/dynablox/assets/12784079/e1de14f4-a909-4504-a969-4b855ea57180

Do you know why is it happening? In the bag files, dynablox is identifying the dynamic obstacles. 

The frequencies are: 
pointcloud: 50Hz
tf: 700Hz
static obstacles (/motion_detector/visualization/detections/object/static): 33Hz

Thank you very much for your attention

**Comment by lidiaxp** [comment]
It is possible to see better in this video. The black points are the static obstacles, the white points are the point cloud points, and there is no dynamic obstacle (even with the cube moving).

https://github.com/ethz-asl/dynablox/assets/12784079/91ac7460-a0a1-46fd-9fb4-dd470d554358

**Comment by lidiaxp** [comment]
Now I can see the markers from /motion_detector/visualization/detections/object/static in "real time", but dynablox still not recognizing the static obstacle. Do you any idea why is it happening?

https://github.com/ethz-asl/dynablox/assets/12784079/043bc534-637d-489c-afe0-cfcd2ddbbadf

**Comment by lidiaxp** [comment]
Hi, 

1. Yeah, it makes sense, I removed this node, thank you. 
2. Sorry, I forgot to update the issue with these data. These are the print:
After processPointcloud                                                                                                                 
cloud_size: 5760                                                                                                                        
After setUpPointMap                                                                                                                     
cloud_size: 5760                                                                                                                        
point_map_size: 61                                                                                                                      
occupied_ever_free_voxel_indices_size: 0                                                                                                

After performClustering                                                                                                                 
point_map_size: 61                                                                                                                      
occupied_ever_free_voxel_indices_size: 0                                                                                                

After track                                                                                                                             
cloud_size: 5760                                                                                                                        
clusters_size: 0                                                                                                                        

After processPointCloudMessageAndInsert                                                                                                 
cloud_size: 5760                                                                                                                        
clusters_size: 0         

It means, dynablox is receiving the pointCloud, but is not able to consider occupied voxels along the time (occupied_ever_free_voxel_indices_size: 0). I don't know exactly why. The frequency of my pointCloud is 50hz so probably the problem is not about time. But, maybe due the sparsity of the data considering the Laser gets data each 1 degree. Considering it, I tried to change some parameters in default.yaml to try to identify better sparse data, but no success.

ever_free_integrator:
  counter_to_reset: 1500 
  temporal_buffer: 50   
  burn_in_period: 20   
  tsdf_occupancy_threshold: 0.9 
  neighbor_connectivity: 6

3. The dynamic obstacle is 5 meters away from the Lidar, but I change to 10cm just to guarantee. Thank you. 

Thank you very much for pointed it out. Do you know how can I modify the default.yaml to facilitate the identification of sparse data?

**Comment by lidiaxp** [comment]
I believe the code is getting stuck here:
```
for (const auto& voxel_points_pair : voxel_map) {
    TsdfVoxel& tsdf_voxel =
        tsdf_block->getVoxelByVoxelIndex(voxel_points_pair.first);
    tsdf_voxel.last_lidar_occupied = frame_counter_;

    // This voxel attribute is used in the voxel clustering method: it
    // signalizes that a currently occupied voxel has not yet been clustered
    tsdf_voxel.clustering_processed = false;

    // The set of occupied_ever_free_voxel_indices allows for fast access of
    // the seed voxels in the voxel clustering
    if (tsdf_voxel.ever_free) {
      occupied_ever_free_voxel_indices.push_back(
          std::make_pair(block_index, voxel_points_pair.first));
    }
  }
```

The variable voxel_map is not empty, but the conditional `tsdf_voxel.ever_free` is never true. I don't know exactly how the function `getVoxelByVoxelIndex` works. I trying to modify the Voxels parameters in default.yaml as well.

**Comment by Schmluk** [comment]
Hi @lidiaxp 

Thanks for your interest! Judging by the videos it looks like dynablox is not building the volumetric map, i.e. maybe the tf of the input points is not received or something similar. Can you check that the volumetric map is being built by enabling the mesh or slices topics?

**Comment by lidiaxp** [comment]
Hi @Schmluk , thank you for your answer. Sure, the volumetric map “ever_free” is always empty, the “never_free” has data. 
To make it identify the dynamic obstacle I modified the code
```
if (!neighbor_occupied_or_unobserved) {
      tsdf_voxel.ever_free = true;
    }
```

To this one: `tsdf_voxel.ever_free = true;`

The main drawback doing it is that when I move the robot I identify some static obstacles as dynamic. 

The variable `neighbor_occupied_or_unobserved` is coming true in this part of the code:
```
if (neighbor_voxel.weight < 1e-6 ||
          neighbor_voxel.last_occupied >
              frame_counter - config_.burn_in_period) {
        neighbor_occupied_or_unobserved = true;
        break;
      }
```

I could not find where it is defined the weight for the voxels, so I do not know why it is happening. Could you give me some insights about it? Also, how can I check if the problem is with tf?

**Comment by Schmluk** [comment]
Hi @lidiaxp ,

Removing that line may be quite detrimental to performance as this essentially removes the the spatial 'high confidence margin'. Can you enable the mesh and slice topics and maybe send attach the images to verify that the map is being built correctly? Did you adjust e.g. the sensor specifics for your simulation?

**Comment by lidiaxp** [comment]
Hi @Schmluk,

Yeah, I realized it when i tried to move the drone. Some static obstacles are considered dynamic since there is no 'high confidence margin'.

Yes, sure. There is nothing in the slices or in the mesh. Also, I took a screenshot showing the volumes, the 'ever free' is empty, and the 'never free' has some cubes.

![Screenshot from 2023-12-13 11-10-49](https://github.com/ethz-asl/dynablox/assets/12784079/9b840135-d433-4825-8f4a-3d917f06cf94)

I also recorded a video showing you the rviz (when I try to show the TSDF everything crashs).

https://github.com/ethz-asl/dynablox/assets/12784079/b6f7d756-7082-4180-96a4-1c1adab9b587

With it, I believe that the map is not being built correct. Do you know why or what can I do to try to solve it?

About the sensor, I am simulating an Velodyne VLP 16 in Unity. 360 degree sensor with 360 beams (1 beam per degree), vertical angle of 20 (-20 to 20) with 16 beams, and a max range of 30m. 

```
float maxVerticalAngle = 20;
float minVerticalAngle = -20;
float maxHorizontalAngle = 360;
float minHorizontalAngle = 0;
int verticalLayers = 16;
int horizontalIncrements = 360;
float maxRange = 30f;

for (int horizontalIncr = 0; horizontalIncr < horizontalIncrements; horizontalIncr++)
      {
          for (int verticalLayer = 0; verticalLayer < verticalLayers; verticalLayer++)
          {
              float verticalAngle = minVerticalAngle + verticalLayer * verticalIncrement;
              float horizontalAngle = minHorizontalAngle + horizontalIncr * horizontalIncrement;

              Vector3 fwd = new Vector3(0, 0, 1);
              Vector3 dir = transform.rotation * Quaternion.Euler(-verticalAngle, horizontalAngle, 0) * fwd;

              RaycastHit hit;
              if (Physics.Raycast(transform.position, dir, out hit, maxRange))
              {
                  send_obstacles_points();
              }
          }
      } 
```

I also tried to increase the number of beams, but the Unity gets too slow.

Thank you very much for your attention.

**Comment by Schmluk** [comment]
Hi @lidiaxp ,

I agree, it seems the problem is with the data subscription rather than the method. Can you make sure all pointclouds are received and have a matching tf transform for their timestamp? Also make sure the global frame set in dynablox exists and is connected to the tf tree. Hope this helps!

**Comment by lidiaxp** [comment]
Probably I am doing something wrong with the connection in the tf tree. When I use just the tf_static the code is as I've shown you before. But, when I use the tf, appear these two errors (not at the same time):

`[ WARN] [1704794739.845279026]: TF_REPEATED_DATA ignoring data with redundant timestamp for frame point_cloud_from_unity at time 1704794739.843836 according to authority unknown_publisher`

`W0109 10:02:00.786875 597602 motion_detector.cpp:217] Could not get sensor transform, skipping pointcloud: Lookup would require extrapolation 0.001551866s into the future.  Requested time 1704794520.778921843 but the latest data is at time 1704794520.777369976, when looking up transform from frame [point_cloud_from_unity] to frame [map]`

All the others things you commented I checked here and they are working. Probably the problem is with the tf connection. Do you have some tip for me of how to solve this problem with the tf? Thank you very much for all your help.

**Comment by lidiaxp** [comment]
Hi, yes. The frequency of the pointcloud is 50hz, so I believe it is being received every time. About the tf tree, I can check it in rviz, and always there is a connection between the tf of the sensor and the global frame. I also noticed that when there is some error in the tf tree dynablox shows some errors, but it is not happening anymore. So, I believe that there is no problem in the tf tree. 

I agree with you that the problem is not the method and yes the data because I am able to use dynablox in other simulators. I just wonder why it is not working in unity if everything looks like the same. Thank you very much for all your help.

**Comment by Schmluk** [comment]
Yes, if the point clouds are wrongly posed (errors in tf) then dynablox can't work as intended. Happy to help, we hope you were able to resolve the remaining issues!
