### ISSUE TITLE
Problem about doals dataset

### ISSUE THREAD

**Issue by jkff00** [ethz-asl/dynablox#22]
The doals dataset provides a point cloud as well as an absolute bitmap (/T_map_os1_lidar), and we extracted the point cloud and interpolated it to get the pose where the point cloud frames are located. However, the maps obtained from the registration have obvious misalignment, which means that there is a large error in the pose. Can you please describe the processing method for this dataset?

**Comment by jkff00** [comment]
![2024-01-31 10-33-04 的屏幕截图](https://github.com/ethz-asl/dynablox/assets/94893280/d12d3b0b-8a8e-461f-8244-1f2d506c586a)

**Comment by Kin-Zhang** [comment]
This lidar undistoration launch need also run:

https://github.com/ethz-asl/dynablox/blob/e9333c4996b1eeb6c3c16244af96b64e3a927e28/dynablox_ros/launch/play_doals_data.launch#L11C1-L17C10

```xml
  <!-- Lidar Undistortion -->
  <node name="lidar_undistortion" pkg="lidar_undistortion" type="lidar_undistortion_node">
    <remap from="pointcloud" to="/os1_cloud_node/points" />
    <remap from="~pointcloud_corrected" to="/pointcloud" />
    <param name="odom_frame_id" value="map" />
    <param name="lidar_frame_id" value="os1_lidar" />
  </node>
```

**Comment by Schmluk** [comment]
Apologies for the late reply, the comment above is absolutely correct so we did not reply earlier. However, even with LiDAR-undistortion we noticed that not all clouds are perfectly aligned, as for some sequences of the data there seems to be a bit of drift in the ground truth poses. This is, among others, why Dynablox was designed robust with respect to drift.
