### ISSUE TITLE
Hi, can dynablox run with a Livox mid-360 or Velodyne VLP-16 Lidar?

### ISSUE THREAD

**Issue by qimao7213** [ethz-asl/dynablox#23]

**Comment by Schmluk** [comment]
Hi @qimao7213 

Thank you for your interest and reaching out! As long as you get posed point clouds and an according sensor model, it should work! For the VLP-16 the current sensor model should definitively work with just updating the params (I think we tried it without guarantees, though). Same for the Livox mid-360! For other solid state lidars (with irregular patterns) the sensor model might need a closer look, although I'd not be surprised if it just works (it only does projection onto a spherical image, where each ray is converted to a bearing vector instead). Hope this helps, let us know how it goes or if you run into problems!
