### ISSUE TITLE
dynablox my own dataset

### ISSUE THREAD

**Issue by batmelody** [ethz-asl/dynablox#24]
Hi,

thanks for your fabulous work about dynamic object detection!

I want to run dynablox with my own dataset. Would you like to give me some advices about how to set up?

Appreciate for your help!

**Comment by haider8645** [comment]
Do you have your own bag files with pointcloud and odometry? If yes, then you need to update the bag_file parameter in the run_experiment.launch. Afterwards update the frame names and pointcloud topic name in the play_doals_data.launch

**Comment by Schmluk** [comment]
@haider8645 That's great to hear! Exactly, from a pipeline perspective as long as you provide posed point clouds (i.e. there is a tf transform for that timestamp) and a suitable sensor model, it should just work! Hope this helps!
