### ISSUE TITLE
questions about real-time adeptation

### ISSUE THREAD

**Issue by himhan34** [ethz-asl/dynablox#26]
Thank you for the great code.
I am currently working with the code and have a few questions.
Is it possible to receive Velodyne points or MID-360 point clouds in real-time and process them using the package?

Also, I noticed in the issues that you mentioned a "localized point cloud."
Does the term "localized point cloud" refer to the point cloud and state that come from other point cloud-based SLAM systems?

thanks for reading

**Comment by Schmluk** [comment]
Hi @himhan34 ,

- Yes, this is possible and done in our demo! 
- Localized means you need a state estimate (pose) for each point cloud. This can be done in real time by using any LiDAR Odometry or SLAM pipeline (in our experiments we ran FAST-LIO2 I think). Dynablox then does the simultaneous dense reconstruction and motion detection part. 
- One more thing to note is that Dynablox works much better if motion compensation is performed on the input point cloud between state estimation and dense mapping. This is also shown in our demo.

Hope this helps!

**Comment by himhan34** [comment]
Thanks for the quick review .! 
I will try and tell you how it works! 
Have a good day!
