### ISSUE TITLE
is there any way to use clustering the dynamic points alone?

### ISSUE THREAD

**Issue by himhan34** [ethz-asl/dynablox#27]
thanks for the really nice repo and code. 
i have tried dataset and seen the result of the clustering.
however as i am using jetson orin 64gb developer kits. the fps of the clustering was  bit slow. 

is there a reason? and if it is possible 
the thing that i wanna accomplishing is using the clustering algorithms alone with fastlio2
not making the TSDF mapping. is it possible?

thanks for the reading and have a great day!
(and i just figured out that dynablox is included in the nvblox, i will try that one and tell you how it works.
again have a great day!)

**Comment by Schmluk** [comment]
Hi @himhan34 

Thanks for your interest! The motion cue leveraged by Dynablox to detect moving objects is free space - which requires building a TSDF. Clustering only happens to group the detected dynamic points but won't do much without the motion detection first.

You can play with larger voxel sizes or lower integration ranges if high framerate is really important t you, or use the more GPU-optimized parallelized version in nvblox. Hope this helps!

**Comment by himhan34** [comment]
thanks for the comment. i will try and tell you the result!

**Comment by Schmluk** [comment]
That sounds great! Looking forward to it!
