### ISSUE TITLE
Sensor Height

### ISSUE THREAD

**Issue by haider8645** [ethz-asl/dynablox#31]
Hello!

could you please tell me the sensor height of the Ouster OS1 64 during data collection?

Best regards,
Haider

**Comment by Schmluk** [comment]
Hi @haider8645 ,

The sensor is mounted on a handheld device, so its height is variable but approximately 2m above ground most of the time. Also, I think we used a OS0 128 beam LiDAR for the collected data. Hope this helps!

**Comment by haider8645** [comment]
Thanks!!
