### ISSUE TITLE
Special card when running the pkg ???

### ISSUE THREAD

**Issue by maomao0220** [ethz-asl/dynablox#5]
hello, when I run your pkg , it is  very stuttering， how to do to improve it ？

**Comment by Schmluk** [comment]
Hi @maomao0220 

Thank you for reaching out!

Can you be more precise with what is not working? Are there any errors printed to your terminal? Does e.g. running `htop` show CPU or memory limitations?

We have run the method on mobile hardware (laptops and NUC) using CPU only. Generally it will process the data as fast as possible so in the worst case it should run a bit slower but still comparably smooth.

**Comment by maomao0220** [comment]
@Schmluk  no errors  printed to my terminal， I use ubuntu18.04 ros melodic ，and when I run  your projects, it was very very slow . I want to know:
1、 your bags were recorded with 20 systems or with 18 systems???Whether the reason for the card is related to TF (in bags)
2、If I only want to remove the point cloud after a dynamic object, how can I simplify the process?

**Comment by maomao0220** [comment]
@Schmluk 
![hahahahaah](https://user-images.githubusercontent.com/64572122/235091705-9607a96d-73c2-4f8e-a215-a83ef093784a.png)

https://user-images.githubusercontent.com/64572122/235092433-f1f490ea-8aa2-4438-97e5-a3c9c379b2ed.mp4

**Comment by maomao0220** [comment]
@Schmluk  How can I to improve it faster?

**Comment by Schmluk** [comment]
HI @maomao0220 

Unfortunately the video supplied can not be played. Few potential suggestions:
* There seem to be some issues with TF, which may take some time to wait for transforms that may lead to your slow experience. This can potentially be alleviated by adding the ros param `use_sim_time=true` to the launch file. 
* Have you compiled the package in release mode? I.e. what does the output of `catkin config` show?
* We have not tested and do not officially support 18.04, although I don't see any reason why it should not work as in 20.04.

Hope this helps!

**Comment by Schmluk** [comment]
Closed due to inactivity.
