### ISSUE TITLE
error: ‘ParseCommandLineFlags’ is not a member of ‘google’

### ISSUE THREAD

**Issue by SnowCarter** [ethz-asl/dynablox#6]
Solved by adding `#include <gflags/gflags.h>` to following two files: 

- dynablox/dynablox_ros/src/cloud_visualizer_node.cpp 
- dynablox/dynablox_ros/src/motion_detector_node.cpp

**Comment by Schmluk** [comment]
Great catch! Please feel free to open a pull request for these changes!
